/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function IconStar(props) {
  const { size, color, ...other } = props;
  return (
    <svg
      version="1.1"
      id="svg-star"
      x="0px"
      y="0px"
      viewBox="0 0 1134 972"
      height={size}
      width={size}
      {...other}
    >
      <g>
        <g>
          <path
            d="M968,428c-61.7,70.5-171.7,187.5-171.7,187.5s17.6,128.2,28.2,215.8c4.7,44.7-30,64.1-68.8,46.4
			c-74.1-34.7-187-88.8-212.2-101.1c-25.9,11.8-139.3,65.3-214,99.9c-39.4,17.1-74.1-1.8-70-46.4c10-87.6,28.2-215.2,28.2-215.2
			S176.7,498.5,114.3,428c-22.3-25.9-7.6-62.3,35.9-68.8c89.4-15.9,227.5-41.2,227.5-41.2s75.8-130.5,123.5-210.5
			c26.5-48.8,44.7-42.9,47.6-41.7c8.2,2.4,21.2,12.3,37.6,41.7c47,80,121.7,210.5,121.7,210.5s136.4,25.3,224.6,41.2
			C975.6,365.7,989.7,402.7,968,428L968,428z M968,428"
          />
        </g>
      </g>
    </svg>
  );
}

IconStar.defaultProps = {
  color: "currentColor",
  size: 24
};

IconStar.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number])
};
