/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function IconArrowRightCircle(props) {
  const { size, color, ...other } = props;
  return (
    <svg
      version="1.1"
      id="svg-arrow-right-circle"
      x="0px"
      y="0px"
      viewBox="0 0 612 792"
      height={size}
      width={size}
      {...other}
    >
      <g>
        <g fill={color}>
          <defs>
            <rect
              id="arrow-right-circle@SVGID_1_"
              x="-33.5"
              y="58.5"
              width="677.8"
              height="676.8"
            />
          </defs>
          <path
            d="M643.3,397.2c0,93.4-37.8,177.9-99,239.1c-61.2,61.3-145.7,99.1-239.1,99.1c-93.4,0-177.9-37.9-239.1-99.1
			C4.8,575.1-33,490.6-33,397.2c0-93.3,37.9-177.9,99-239.1c61.2-61.1,145.7-99,239.1-99c93.4,0,177.9,37.9,239.1,99
			C605.5,219.3,643.3,303.8,643.3,397.2L643.3,397.2z M340.5,561.9c-6.3,6.3-6.3,16.6,0,22.9c6.4,6.3,16.6,6.3,22.9,0l175.9-175.9
			l0.3-0.3c2.9-2.9,4.8-7,4.8-11.5c0-4.4-1.8-8.5-4.8-11.4l-0.3-0.3L363.4,209.6c-6.3-6.3-16.6-6.3-22.9,0c-6.3,6.3-6.3,16.6,0,22.9
			L488.9,381H82.2c-8.9,0-16.2,7.3-16.2,16.2c0,9,7.3,16.3,16.2,16.3h406.7L340.5,561.9z M305.1,91.5c-84.4,0-160.9,34.2-216.2,89.6
			C33.6,236.3-0.6,312.8-0.6,397.2c0,84.5,34.2,160.9,89.5,216.2c55.3,55.3,131.8,89.5,216.2,89.5c84.4,0,160.9-34.2,216.2-89.5
			c55.3-55.3,89.5-131.8,89.5-216.2c0-84.4-34.2-160.8-89.5-216.2C466,125.7,389.6,91.5,305.1,91.5L305.1,91.5z M305.1,91.5"
            clipPath="url(#arrow-right-circle@SVGID_1_)"
          />
        </g>
      </g>
    </svg>
  );
}

IconArrowRightCircle.defaultProps = {
  color: "currentColor",
  size: 24
};

IconArrowRightCircle.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number])
};
