/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function IconCaretDown(props) {
  const { size, color, ...other } = props;
  return (
    <svg
      version="1.1"
      id="svg-caret-down"
      x="0px"
      y="0px"
      viewBox="0 0 612 792"
      height={size}
      width={size}
      {...other}
    >
      <g>
        <g>
          <defs>
            <rect
              id="caret-down@SVGID_1_"
              x="74"
              y="260"
              width="463"
              height="272.9"
            />
          </defs>
          <path
            d="M525.8,270.8c-7.7-7.7-17.9-10.2-28.2-10.2l-384,2.6c-10.2,0-20.5,2.6-28.2,10.2c-15.4,15.4-15.4,38.4,0,53.8
			l192,192c2.6,2.6,7.7,5.1,10.2,7.7l2.6,2.6c12.8,5.1,30.7,2.6,41-7.7l192-194.6C541.2,309.2,538.6,286.2,525.8,270.8L525.8,270.8z
			 M525.8,270.8"
          />
        </g>
      </g>
    </svg>
  );
}

IconCaretDown.defaultProps = {
  color: "currentColor",
  size: 24
};

IconCaretDown.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number])
};
