/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function IconEggs(props) {
  const { size, color, ...other } = props;
  return (
    <svg
      version="1.1"
      id="svg-eggs"
      x="0px"
      y="0px"
      viewBox="0 0 612 792"
      height={size}
      width={size}
      {...other}
    >
      <path
        d="M306.1,37C178.8,37,43.5,216.4,43.5,411.8c0,195.4,140,320,261.8,320c0.3,0,0.6,0,0.8,0c0,0,0.4,0,0.7,0
	c121.7,0,261.6-124.6,261.6-320C568.5,216.4,432.4,37,306.1,37 M315.8,701.6l-10.4,0.2l-0.8,0c-97.5-0.6-231.8-101.1-231.8-289.3
	c0-187,128.5-347.2,233.6-347.2c50,0,107.3,37.9,153.4,101.3c50.8,70,79.9,159.6,79.9,245.9C539.8,595.8,412.5,695.9,315.8,701.6"
      />
      <path d="M142.6,360l23.6,1.2c5.7-58.7,29.8-109.6,53.8-129.9l-14-28.6C175.5,231.3,148.7,292.2,142.6,360" />
    </svg>
  );
}

IconEggs.defaultProps = {
  color: "currentColor",
  size: 24
};

IconEggs.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number])
};
