/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function IconNutrient(props) {
  const { size, color, ...other } = props;
  return (
    <svg
      version="1.1"
      id="svg-nutrient"
      x="0px"
      y="0px"
      viewBox="0 0 612 792"
      height={size}
      width={size}
      {...other}
    >
      <g>
        <g>
          <defs>
            <rect
              id="svg-nutrient@SVGID_1_"
              x="-43"
              y="48"
              width="697.9"
              height="697.9"
            />
          </defs>
          <path
            d="M380.4,159.2c-8.2,8.2-8.2,20.5,0,28.7c8.2,8.2,20.5,8.2,28.7,0c28.7-28.7,77.8-28.7,106.5,0
			c4.1,4.1,10.2,6.1,14.3,6.1c4.1,0,10.2-2,14.3-6.1c8.2-8.2,8.2-20.5,0-28.7C499.2,114.2,425.5,114.2,380.4,159.2L380.4,159.2z
			 M380.4,159.2"
            clipPath="url(#svg-nutrient@SVGID_1_)"
          />
          <path
            d="M597.5,106c-36.9-36.9-88.1-57.3-137.2-57.3c-49.2,0-98.3,18.4-137.2,57.3L13.8,415.2
			c-75.8,75.8-75.8,198.7,0,272.4C50.7,724.5,101.9,745,151,745s98.3-18.4,137.2-57.3l309.2-309.2
			C673.3,302.6,673.3,179.7,597.5,106L597.5,106z M259.6,658.9C230.9,687.6,192,704,151,704c-41,0-79.9-16.4-108.5-45.1
			c-59.4-59.4-59.4-155.6,0-215l141.3-141.3l215,215L259.6,658.9z M568.8,349.7L427.5,491L210.4,273.9l141.3-141.3
			c28.7-28.7,67.6-45.1,108.5-45.1c41,0,79.9,16.4,108.5,45.1C628.2,194,628.2,290.3,568.8,349.7L568.8,349.7z M568.8,349.7"
            clipPath="url(#svg-nutrient@SVGID_1_)"
          />
        </g>
      </g>
    </svg>
  );
}

IconNutrient.defaultProps = {
  color: "currentColor",
  size: 24
};

IconNutrient.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number])
};
