/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function IconNutrVd(props) {
  const { size, color, ...other } = props;
  return (
    <svg
      version="1.1"
      id="svg-nutr-vd"
      x="0px"
      y="0px"
      viewBox="0 0 612 792"
      height={size}
      width={size}
      {...other}
    >
      <g>
        <path
          d="M603.8,280.7l-101.6-125V56.4c0-14-12.2-25.4-27.2-25.4H142.8c-15,0-27.2,11.3-27.2,25.4v98.5L8.5,271.5
		C4.3,276.1,2,281.9,2,288v447.3c0,14,12.2,25.4,27.2,25.4h552.9c15,0,27.2-11.4,27.2-25.4V296C609.3,290.4,607.4,285.1,603.8,280.7
		L603.8,280.7z M468.6,60.8V142H149.1V60.8H468.6z M42.5,303.2h232.9c9,0,16.3-6.8,16.3-15.2c0-8.4-7.3-15.2-16.3-15.2H58.1
		c0,0,92.1-99.9,92.4-100.3h292.4l-87.2,107.4c-3.9,4.5-6.1,10.1-6.1,15.9v428.1H42.5V303.2z M568.8,723.8H390.2V297.8l84.9-110.7
		l93.7,110.4V723.8z M568.8,723.8"
        />
      </g>
    </svg>
  );
}

IconNutrVd.defaultProps = {
  color: "currentColor",
  size: 24
};

IconNutrVd.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number])
};
