/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function IconArrowDown(props) {
  const { size, color, ...other } = props;
  return (
    <svg
      version="1.1"
      id="svg-arrow-down"
      x="0px"
      y="0px"
      viewBox="0 0 612 792"
      height={size}
      width={size}
      {...other}
    >
      <g>
        <g>
          <defs>
            <rect
              id="svg-arrow-down@SVGID_1_"
              x="-2"
              y="233"
              width="614.9"
              height="326.9"
            />
          </defs>
          <path
            d="M293.1,528.2l290.1-290.1c6.8-6.8,17.1-6.8,23.9,0c6.8,6.8,6.8,17.1,0,23.9L317,553.8
			c-6.8,6.8-17.1,6.8-23.9,0C286.3,547,286.3,535,293.1,528.2L293.1,528.2z M293.1,528.2"
            clipPath="url(#svg-arrow-down@SVGID_1_)"
          />
          <path
            d="M26.9,239.8L317,529.9c6.8,6.8,6.8,17.1,0,23.9c-6.8,6.8-17.1,6.8-23.9,0L3,263.7c-6.8-6.8-6.8-17.1,0-23.9
			C8.1,232.9,20.1,232.9,26.9,239.8L26.9,239.8z M26.9,239.8"
            clipPath="url(#svg-arrow-down@SVGID_1_)"
          />
        </g>
      </g>
    </svg>
  );
}

IconArrowDown.defaultProps = {
  color: "currentColor",
  size: 24
};

IconArrowDown.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number])
};
