/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function IconTurnOff(props) {
  const { size, color, ...other } = props;
  return (
    <svg
      version="1.1"
      id="svg-turn-off"
      x="0px"
      y="0px"
      viewBox="0 0 612 792"
      height={size}
      width={size}
      {...other}
    >
      <path d="M-404.7,484.2" />
      <g>
        <path
          d="M298,627.7c-121.6,0-220.6-97.5-220.6-217.2c0-82,47.3-157.4,121.6-195.1c9-4.4,20.3,0,24.8,8.9c4.5,8.9,0,20-9,24.4
		c-63,31-101.3,93.1-101.3,161.8c0,99.8,83.3,181.8,184.6,181.8c101.3,0,184.6-82,184.6-181.8c0-68.7-38.3-130.8-103.6-161.8
		c-9-4.4-13.5-15.5-9-24.4c4.5-8.9,15.8-13.3,24.8-8.9c76.5,37.7,121.6,110.8,121.6,195.1C518.6,530.2,419.5,627.7,298,627.7
		L298,627.7z"
        />
        <path d="M298,366.8c-9,0-18-9-18-18V157.5c0-9,9-18,18-18c9,0,18,9,18,18v191.4C316,357.8,307,366.8,298,366.8L298,366.8z" />
        <path d="M298,400.3" />
        <rect x="77.4" y="172.6" width="439.2" height="455.7" />
      </g>
    </svg>
  );
}

IconTurnOff.defaultProps = {
  color: "currentColor",
  size: 24
};

IconTurnOff.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number])
};
