/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function IconMeatVegDish(props) {
  const { size, color, ...other } = props;
  return (
    <svg
      version="1.1"
      id="svg-meat-veg-dish"
      x="0px"
      y="0px"
      viewBox="0 0 612 792"
      height={size}
      width={size}
      {...other}
    >
      <g fill={color}>
        <path
          d="M663.6,677.5h-717c-14.1,0-25.6,11.5-25.6,25.6c0,14.1,11.5,25.6,25.6,25.6h717c14.1,0,25.6-11.5,25.6-25.6
		C689.2,689,677.6,677.5,663.6,677.5L663.6,677.5z M663.6,677.5"
        />
        <path
          d="M253.9,114.2c0,28.3,22.9,51.2,51.2,51.2c28.3,0,51.2-22.9,51.2-51.2c0-28.3-22.9-51.2-51.2-51.2
		C276.8,63,253.9,85.9,253.9,114.2L253.9,114.2z M253.9,114.2"
        />
        <path
          d="M-53.4,626.1v0.2h717v-0.2c14.6-0.6,25.7-13.2,24.6-28C674.8,413.6,531,265.2,348.6,244.7l-9.8-29.4
		c-4.8-14.5-18.4-24.3-33.7-24.3c-15.3,0-28.9,9.8-33.7,24.3l-9.8,29.4C79.2,265.2-64.6,413.6-78,598.1
		C-79,612.8-68,625.6-53.4,626.1L-53.4,626.1z M305.1,293.4c166.4,0,304.2,122.2,328.8,281.7H-23.7C1,415.6,138.7,293.4,305.1,293.4
		L305.1,293.4z M305.1,293.4"
        />
      </g>
    </svg>
  );
}

IconMeatVegDish.defaultProps = {
  color: "currentColor",
  size: 24
};

IconMeatVegDish.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number])
};
