/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function IconFishes(props) {
  const { size, color, ...other } = props;
  return (
    <svg
      version="1.1"
      id="svg-fishes"
      x="0px"
      y="0px"
      viewBox="0 0 612 792"
      height={size}
      width={size}
      {...other}
    >
      <g fill={color} stroke={color} strokeWidth="19">
        <path
          d="M117.8,439.1l-89.9,63.7c-2.5,1.8-6,1.8-8.6,0.1c-2.6-1.7-3.7-4.8-2.7-7.6c20.9-59.3,31.9-94.3,33.1-105
		c1.2-10.6-2.3-41.4-10.4-92.4c-0.5-2.9,1.1-5.7,3.8-7c2.8-1.3,6.1-0.8,8.3,1.2l78.4,71.7c68.4-81.2,152.4-119.9,252.2-116.3
		c137.3,5,216.7,92,213.6,176c-3,84-88.6,165-225.8,160C260.3,579.6,176.3,531.5,117.8,439.1L117.8,439.1z M117.8,439.1"
        />
        <path
          d="M275.9,496.3c32.2,1.2,52.6-7.3,61.1-25.4c12.8-27.2-17.4-37.2-45.6-38.2c-13.2-0.5-27.5,17-46.5,30.4
		C228.7,474.4,239.1,485.5,275.9,496.3L275.9,496.3z M275.9,496.3"
        />
        <path d="M473.1,561.5c-33.8-43.3-47.4-66.2-47.2-145.4C426,354.3,440.2,312.8,477,272" />
        <path d="M275.9,496.3" />
        <path d="M272.4,495.3" />
        <path d="M327.5,440.8" />
        <g>
          <path d="M177.9,294.7c10.4-29.3,25.3-51.4,44.1-65.8c19.1-14.7,42.6-21.6,69.7-20.6c32.7,1.2,59.5,12.1,79.7,32.4" />
          <path d="M114.7,420.8" />
        </g>
        <path
          d="M493.6,405.1c-0.4,11.1,8.3,20.5,19.4,20.9c11.1,0.4,20.5-8.3,20.9-19.4c0.4-11.1-8.3-20.5-19.4-20.9
		C503.3,385.3,494,394,493.6,405.1L493.6,405.1z M493.6,405.1"
        />
      </g>
    </svg>
  );
}

IconFishes.defaultProps = {
  color: "currentColor",
  size: 24
};

IconFishes.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number])
};
