/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function IconNutrFolicAcid(props) {
  const { size, color, ...other } = props;
  return (
    <svg
      version="1.1"
      id="svg-nutr-folic-acid"
      x="0px"
      y="0px"
      viewBox="0 0 612 792"
      height={size}
      width={size}
      {...other}
    >
      <g>
        <defs>
          <rect
            id="svg-nutr-folic-acid@SVGID_1_"
            x="110"
            y="77"
            width="391.9"
            height="638.9"
          />
        </defs>
        <path
          d="M409.1,714.9H202.2c-52.8-2-94-46.4-92.2-99.2V296.3c-1.1-49.4,34.9-91.7,83.8-98.6h215.2
		c2.7-0.2,5.5-0.2,8.2,0c49,6.8,85,49.2,84,98.6v319.5C503.1,668.6,461.8,712.9,409.1,714.9L409.1,714.9z M202.2,230.9h-5.1
		c-31.5,5.1-54.2,32.8-52.9,64.7v320.2c-1.8,33.9,24.1,62.9,58,65h206.8c33.9-2.1,59.8-31.1,58-65V296.3
		c1.6-32.1-21.2-60.3-52.9-65.4H202.2z M202.2,230.9"
          clipPath="url(#svg-nutr-folic-acid@SVGID_1_)"
        />
      </g>
      <path
        d="M433.6,230.9h-256c-28.3,0-51.2-22.9-51.2-51.2v-51.2c0-28.3,22.9-51.2,51.2-51.2h256c28.3,0,51.2,22.9,51.2,51.2v51.2
	C484.8,208,461.9,230.9,433.6,230.9L433.6,230.9z M177.6,111.4c-4.5,0-8.9,1.8-12.1,5c-3.2,3.2-5,7.5-5,12.1v51.2
	c0,9.4,7.6,17.1,17.1,17.1h256c4.5,0,8.9-1.8,12.1-5c3.2-3.2,5-7.5,5-12.1v-51.2c0-4.5-1.8-8.9-5-12.1c-3.2-3.2-7.5-5-12.1-5H177.6z
	"
      />
      <path
        d="M476.3,367.4H135c-9.4,0-17.1-7.6-17.1-17.1c0-9.4,7.6-17.1,17.1-17.1h341.3c9.4,0,17.1,7.6,17.1,17.1
	C493.4,359.8,485.7,367.4,476.3,367.4L476.3,367.4z"
      />
      <path
        d="M476.3,589.3H135c-9.4,0-17.1-7.6-17.1-17.1c0-9.4,7.6-17.1,17.1-17.1h341.3c9.4,0,17.1,7.6,17.1,17.1
	C493.4,581.7,485.7,589.3,476.3,589.3L476.3,589.3z"
      />
      <path d="M476.3,589.3" />
      <text transform="matrix(0.8382 0 0 1 190.5005 490.9326)">Fibre</text>
    </svg>
  );
}

IconNutrFolicAcid.defaultProps = {
  color: "currentColor",
  size: 24
};

IconNutrFolicAcid.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number])
};
